version: "3.9"

services:
  lagrange:
    container_name: lagrange
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Stockholm
      - DISPLAY=$DISPLAY
    volumes:
      - ./:/home/ros/ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    tty: true
    command: tail -f /dev/null
